### ISSUE TITLE
Master Issue for threading issues

### ISSUE THREAD

**Issue by bobtwinkles** [tjcsl/cslbot#1000]
In order to keep myself and everyone else somewhat sane, I'll be using this issue to track progress of the threading system cleanup. So far the issues that this on depends on (that I know of...) are:

  - [ ] #654 - kill runaway threads that go on for too long and provide notification
  - [ ] #959 - add reload --force which kills all threads/workers
  - [ ] #931 - fix sorting order of !threads
  - [ ] #905 - investigate moving defer to use multiprocessing instead of threading
  - [ ] #665 - add !cancel list
  - [ ] #634 - store kicks so when the bot is oped it can kick cap lock abusers
  - [ ] #905 - investigate moving defer to use multiprocessing instead of threading

**Comment by sckasturi** [comment]
wow you really wanted to make the thousandth issue special, didnt you?
