### ISSUE TITLE
Convert-to-argparse tracker

### ISSUE THREAD

**Issue by creffett** [tjcsl/cslbot#1003]
Tracker for issues either involving or best fixed by converting stuff to use ArgParse:
- [ ] #985 - make the parse_args try catch pattern into a function we can call
- [ ] #965 - update filter to support multiple chained filters in one command
- [ ] #946 - move filter to argparse
- [ ] #896 - allow !timeout to take more than one argument
- [ ] #877 - make ignore take a time to ignore for
- [ ] #665 - add !cancel list
- [ ] #662 - merge !defersay and !cancel into !defer {say,cancel}
- [ ] #661 - allow deferals to be extended or shortened (this and the two above can be done as a group)
